---
title: "HW3_Patrick Neyland"
author: "Patrick Neyland"
date: '2022-09-13'
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = NA)
library(tidyverse)
```
# Appendix A
## Question 1
### Setup
```{r}
df <- data.frame(Family = c(1,2,3,4,5,6,7,8,9,10),"Monthly Expenditures" = c(300,440,350,1100,640,480,450,700,670,530))
avg_exp <- mean(df$Monthly.Expenditures)
med_exp <- median(df$Monthly.Expenditures)
mean((df$Monthly.Expenditures)*100)
avg_exp*100
med_exp*100
df2 <- data.frame(Family = c(1,2,3,4,5,6,7,8,9,10),"Monthly Expenditures" = c(300,440,350,1100,640,480,450,900,670,530))
avg_exp2 <- mean(df2$Monthly.Expenditures)
avg_exp2
med_exp2 <- median(df2$Monthly.Expenditures)
med_exp2
```
The mean is increased by 20 while the median does not change. 


## Question 2
###
```{r}
100*1.15

115*1.18
135.7/115


.18/.15
.15*1.2
```


## Question 3
### Part (i)

```{r}
exper1 <- 0
exp_0 <- exp(10.6+(0.027*exper1))
exper2 <- 5
exp_5 <- exp(10.6+(0.027*exper2))
```
The salary when $education=0$ 

#How to eliminate scientific notation in markdown output. 


```{r}
salary <- function(education) {
  exp(10.3+(0.06*education))
}

salary(0)

exp1 <- 0
exp0 <- exp(10.3+(0.6))
```


### Part (ii)
```{r}
(100*0.027)*5
```
### Part (iii)
```{r}
((exp_5-exp_0)/exp_0)*100
```
The estimator gives a change on 13.5 percent while the model has a change of 14.45 percent. 

## Question 4
### Part (i)
```{r}
pnorm(5,3,sqrt(2), lower.tail = TRUE)
```
### Part (ii)
```{r}
pnorm(2,3,sqrt(2), lower.tail = FALSE)
```
### Part (iii)
```{r}
pnorm(3,mean= 3,sd = sqrt(2)) + (pnorm(5,mean = 3,sd = sqrt(2), lower.tail = FALSE))
```

## Question 5

1-F(.57)